"""empty message

Revision ID: 044d205f2e60
Revises: 0b133db09b2f
Create Date: 2017-04-14 18:23:48.902175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '044d205f2e60'
down_revision = '0b133db09b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t1')
    op.add_column('printers', sa.Column('horizontal_flip', sa.Boolean(), nullable=True))
    op.add_column('printers', sa.Column('vertical_flip', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printers', 'vertical_flip')
    op.drop_column('printers', 'horizontal_flip')
    op.create_table('t1',
    sa.Column('idnew_table', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('idnew_table'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
